add PKGBUILD
mimium-org/mimium pull request #49
Opened 2021-02-13 12:33 UTC by Inqb8tr-jp

Arch LinuxのPKGBUILDを作成しました。
[AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines)

2021-02-14 16:22 UTC, tomoyanonymous commented
ありがとうございます！github actionsで自動アップロードできそうなのでここから少しコミット積んでみていいでしょうか？
https://github.com/marketplace/actions/publish-aur-package

2021-02-25 08:11 UTC, tomoyanonymous commented
ちょっとAURについてちゃんと調べたのですが、リリースした後にPKGBUILDのチェックサムを作る必要があるので、運用方法としては2通りになるのかなーと。

1. PKGBUILD自体は(テンプレートとして一応マージはするけど)このリポジトリでバージョン管理せずに、@Inqb8tr-jp さんがmimiumの新バージョンリリースのたびにバージョン部分とsha256部分を書き換えてAURにコミット&プッシュする。
2. リリースのCIプロセスにhttps://github.com/marketplace/actions/arch-linux-pkgbuild-builder-action https://github.com/marketplace/actions/publish-aur-package の2つを入れて、リリースするたびに自動でバージョンとsha256を更新、AURに自動でコミット&プッシュする。

2は検証に少し時間かかりそうなので、ひとまず1.の状態で運用しばらくしておく感じで様子みるのでどうでしょうか？

2021-02-25 08:17 UTC, tomoyanonymous requested changes
実際に検証ができてないのでなんともなのですが、一応気になったところだけコメント残しておきました。

2021-02-25 08:17 UTC, tomoyanonymous commented on PKGBUILD
> +arch=('x86_64' 'i686')
i686は未サポートなのでとりあえずx86_64だけで良いかと。

2021-02-25 08:17 UTC, tomoyanonymous commented on PKGBUILD
> +# Maintainer: <ameniutaeba1978 at gmail dot com>
一応
`# Contributer: Tomoya Matsuura <me at matsuuratomoya dot com>`
と加えておいてもらえるとありがたいです

2021-02-25 08:17 UTC, tomoyanonymous commented on PKGBUILD
> +  cd "build"
SuperColliderのPKGBUILDを読んだのですが、こんな感じで、
https://github.com/archlinuxarm/PKGBUILDs/blob/3b9d9b309a42d0e71752448a911b55fe1b7d0649/community/supercollider/PKGBUILD#L89

` depends+=('libasound.so' 'libsndfile.so')`の記述は必要かもしれません（試してみないとよくわからないのですが）

2021-02-26 09:19 UTC, Inqb8tr-jp commented on PKGBUILD
> +# Maintainer: <ameniutaeba1978 at gmail dot com>
すみません。
自分のメールアドレスをMaintainerなどと入れてしまっていました。
消しておきますね。

2021-02-26 09:20 UTC, Inqb8tr-jp commented on PKGBUILD
> +  cd "build"
一度クリーンインストールしたPCから試してみますね。

2021-02-26 09:20 UTC, Inqb8tr-jp commented on PKGBUILD
> +arch=('x86_64' 'i686')
了解です。

2021-02-27 06:03 UTC, Inqb8tr-jp commented on PKGBUILD
> +  cd "build"
すみません。クリーンインストールしたManjaro LinuxでPKGBUILDからmakepkg -siで問題なくmimiumがインストールできて動作しました。が、自分があまりにもGithubに不慣れでちょっとすぐにどうとかなる状況でありません（編集し直したものをアップロードすることもすぐにはできません）。また他にやることもあるので、あまりそれだけに時間をかけることもできません。また、もしtomoyanonymousさんの方で余裕があるようなら、Arch、Manjaro用のPKGBUILDを公開していただけないでしょうか。お手数ばかりおかけしたようですみませんでした。よろしくお願いいたします。

2021-03-09 15:13 UTC, tomoyanonymous commented on PKGBUILD
> +  cd "build"
すみませんこちらコメント見落としてました。ひとまずこれで自動CI回せるか別PR立ててみますね。

2021-03-09 15:14 UTC, merged